apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    jsonData:
      defaultDatabase: default
      server: clickhouse
      port: 8123
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: ""
