# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: news.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'news.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnews.proto\x12\x07\x66innews\"}\n\nArticleRaw\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x14\n\x0cpublished_ts\x18\x06 \x01(\x03\x12\x13\n\x0bingested_ts\x18\x07 \x01(\x03\"\x8b\x01\n\x0c\x41rticleClean\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0c\n\x04\x62ody\x18\x05 \x01(\t\x12\x14\n\x0cpublished_ts\x18\x06 \x01(\x03\x12\r\n\x05hints\x18\x07 \x03(\t\x12\x10\n\x08language\x18\x08 \x01(\t\"\x83\x01\n\x0f\x41rticleEnriched\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x14\n\x0cpublished_ts\x18\x04 \x01(\x03\x12\x0f\n\x07tickers\x18\x05 \x03(\t\x12\x10\n\x08\x65ntities\x18\x06 \x03(\t\x12\x0e\n\x06topics\x18\x07 \x03(\t\"v\n\rArticleScored\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07tickers\x18\x02 \x03(\t\x12\x11\n\tsentiment\x18\x03 \x01(\x02\x12\x0e\n\x06topics\x18\x04 \x03(\t\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x11\n\tscored_ts\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'news_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARTICLERAW']._serialized_start=23
  _globals['_ARTICLERAW']._serialized_end=148
  _globals['_ARTICLECLEAN']._serialized_start=151
  _globals['_ARTICLECLEAN']._serialized_end=290
  _globals['_ARTICLEENRICHED']._serialized_start=293
  _globals['_ARTICLEENRICHED']._serialized_end=424
  _globals['_ARTICLESCORED']._serialized_start=426
  _globals['_ARTICLESCORED']._serialized_end=544
# @@protoc_insertion_point(module_scope)
