# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scorer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scorer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cscorer.proto\x12\x07\x66innews\"7\n\x0cScoreRequest\x12\n\n\x02id\x18\x01 \x03(\t\x12\r\n\x05title\x18\x02 \x03(\t\x12\x0c\n\x04\x62ody\x18\x03 \x03(\t\"F\n\rScoreResponse\x12\x11\n\tsentiment\x18\x01 \x03(\x02\x12\x12\n\nconfidence\x18\x02 \x03(\x02\x12\x0e\n\x06topics\x18\x03 \x03(\t2E\n\x06Scorer\x12;\n\nBatchScore\x12\x15.finnews.ScoreRequest\x1a\x16.finnews.ScoreResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scorer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCOREREQUEST']._serialized_start=25
  _globals['_SCOREREQUEST']._serialized_end=80
  _globals['_SCORERESPONSE']._serialized_start=82
  _globals['_SCORERESPONSE']._serialized_end=152
  _globals['_SCORER']._serialized_start=154
  _globals['_SCORER']._serialized_end=223
# @@protoc_insertion_point(module_scope)
